const CUSTOMER_SITES = {
    qiqi: {
        api: 'https://www.qiqidys.com/api.php/provide/vod',
        name: '七七资源',
    },
    yingshigongchang:{
        api:'https://cj.lziapi.com/api.php/provide/vod/',
        name:'影视工厂',
    },
    fantuanyingshi:{
        api:'https://www.fantuan.tv/api.php/provide/vod/',
        name:'饭团影视',
    },
    liangziziyuan:{
        api:'http://cj.lziapi.com/api.php/provide/vod/',
        name:'量子资源',
    },
    yinghuaziyuan:{
        api:'https://m3u8.apiyhzy.com/api.php/provide/vod/',
        name:'樱花资源',
    },
    shandianziyuan:{
        api:'http://sdzyapi.com/api.php/provide/vod/',
        name:'闪电资源',
    },
    guangsuziyuan:{
        api:'https://api.guangsuapi.com/api.php/provide/vod/',
        name:'光速资源',
    },
    kuaiapi:{
        api:'https://api.ukuapi88.com/api.php/provide/vod/',
        name:'酷爱资源',
    },
    zyapi:{
        api:'https://m3u8.apiyhzy.com/api.php/provide/vod/',
        name:'贼歪资源',
    },
    moduziyuan:{
        api:'https://caiji.moduapi.cc/api.php/provide/vod',
        name:'魔都资源',
    },
    sanliulingziyuan:{
        api:'https://360zy.com/api.php/seaxml/vod',
        name:'360资源',
    },
    aidanziyuan:{
        api:'https://lovedan.net/api.php/provide/vod',
        name:'艾丹资源'
    },
    suoniziyuan:{
        api:'https://suoniapi.com/api.php/provide/vod',
        name:'索尼资源',
    },
    shandianziyuan:{
        api:'http://sdzyapi.com/api.php/provide/vod/',
        name:'闪电资源',
    },
    jisuziyuan:{
        api:'https://jszyapi.com/api.php/provide/vod',
        name:'极速资源',
    },
    guangsuziyuan:{
        api:'https://api.guangsuapi.com/api.php/provide/vod',
        name:'光速资源',
    },
    wolongziyuan:{
        api:'https://collect.wolongzyw.com/api.php/provide/vod',
        name:'卧龙资源',
    },
    youkuziyuan:{
        api:'https://api.ukuapi.com/api.php/provide/vod',
        name:'优酷资源',
    },
    piaolingziyuan:{
        api:'https://p2100.net/api.php/provide/vod',
        name:'飘零资源',
    },
    shenmaziyuan:{
        api:'https://img.smdyw.top/api.php/provide/vod',
        name:'神马资源',
    },
    mayunziyuan:{
        api:'https://api.1080zyku.com/inc/apijson.php/',
        name:'马云资源',
    },
    suboziyuan:{
        api:'https://subocaiji.com/api.php/provide/vod',
        name:'速播资源',
    },
    hongniuziyuan:{
        api:'https://www.hongniuzy2.com/api.php/provide/vod',
        name:'红牛资源',
    },
    huohuziyuan:{
        api:'https://hhzyapi.com/api.php/provide/vod',
        name:'火狐资源',
    },
    wujinziyuan3:{name:"无尽资源资源",api:"https://api.wujinapi.com/api.php/provide/vod/"},
    bubugaoziyuan:{name:"步步高资源",api:"https://api.yparse.com/api/json"},
    CKziyuan:{name:"CK资源",api:"https://ckzy.me/api.php/provide/vod/"},
    jinyingziyuan:{name:"金鹰资源1",api:"https://jyzyapi.com/api.php/provide/vod/"},
    jinyingziyuan2:{name:"金鹰资源",api:"https://jyzyapi.com/provide/vod/from/jinyingm3u8/"},

};

// 调用全局方法合并
if (window.extendAPISites) {
    window.extendAPISites(CUSTOMER_SITES);
} else {
    console.error("错误：请先加载 config.js！");
}
